### PR TITLE
Markdown notes Update

### PR DESCRIPTION
**Pull request by haitianxu2024**
We have made the basic MD notes appeared, ready to merge

### CODE REVIEW

**Comment by haitianxu2024** [comment]
Branch Rebased finished

**Comment by haitianxu2024** [comment]
CI Issue fixed

**Review by Yashraj19 — APPROVED** [review]

**Comment by Yashraj19** [comment]
@ishanppendse i have tested the PR functionality can you resolve the conflict and merge it

**Comment by haitianxu2024** [comment]
I have rebased the branch and resolve the merging conflict, feel free to merge

**Review by Yashraj19 — APPROVED** [review]

**Pull request merged**
